### ISSUE TITLE
Project Goals?

### ISSUE THREAD

**Issue by prologic** [udhos/conbox#1]
Whilst you have listed similar projects as being inactive (_true from my own analysis_) what are your  stated project goals here? Do you intend to incorporate those projects here (_they do implement some applets you don't have_), Do you intend to go further? What is the intended use of conbox? As a direct replacement for `busybox`?

**Comment by udhos** [comment]
> Whilst you have listed similar projects as being inactive (_true from my own analysis_) what are your stated project goals here?

Main goal is to create a feasible alternative to BusyBox in pure Go.

> Do you intend to incorporate those projects here (_they do implement some applets you don't have_),

I want to include most "essential" (whatever that means) Unix/Linux command-line utilities. So, yes, many more applets are needed, including those from other projects.

> Do you intend to go further? What is the intended use of conbox? As a direct replacement for `busybox`?

While working with tiny containers, I often find myself resorting to BusyBox as general purpose tool.
Unfortunately I would not consider hacking BusyBox to add features (unless I am really required to do so).
I would benefit from BusyBox in Go since it would be arguably more hackable.
I don't see conbox as a direct replacement for BusyBox (though I don't oppose that either), but as a similar tool in Go that could be easily hacked (adding and customizing applets) to fit specific needs.

**Comment by prologic** [comment]
Cool! Thanks for the response!

I'd be really interested in getting conbox to a point where I could use it to replace busybox in [mcl](https://mcl.host/) -- For me this would mean the bare minimum set of UNIX utilities that configure a Linux host with some minimal maintainence/debugging tools.

**Comment by udhos** [comment]
I was not aware of mcl. I have just tested it on VirtualBox, and it looked pretty cool! Thanks for pointing it out.

Yeah, hope conbox could eventually get close to BusyBox's feature set as well, but of course that is going to take time. I am currently targeting to include at least the applets of the other similar inactive Go projects. Let's see how fast things evolve. :)
